/**
 * Content Service
 * Fetches content that will eventually come from Hugo-generated JSONs.
 */

// Mock data simulating Hugo's output structure
const MOCKS: Record<string, any> = {
  home: {
    title: "Welcome to LTG",
    description: "This content is being served from a mock service simulating Hugo CMS.",
    sections: []
  },
  events: [
    { id: 1, title: "Commander Tea Party: Edición Real", date: "24 Octubre, 16:00", location: "La Guarida del Dragón, CDMX", type: "Evento Insignia", description: "Nuestra reunión clásica. Trae tu taza de té favorita, tu mazo de Commander y vístete para la corte. Habrá pastelillos y política de mesa.", highlight: true },
    { id: 2, title: "Taller de Encantamientos", date: "05 Noviembre, 11:00", location: "Discord del Reino", type: "Online", description: "Aprende a construir mazos basándote en auras y encantamientos. Ideal para princesas guerreras.", highlight: false },
    { id: 3, title: "Torneo de Bienvenida", date: "15 Noviembre, 10:00", location: "Magic Store Sur", type: "Principiantes", description: "Un ambiente seguro para jugar tu primer torneo sellado. Sin presiones, solo diversión.", highlight: false }
  ],
  podcast: [
    { id: 104, title: "Ep. 4: Etiqueta en la Mesa de Commander", duration: "45 min", date: "10 Octubre", description: "Discutimos los acuerdos tácitos del formato: ¿Cuándo es correcto atacar a quien no tiene bloqueadores? ¿Se vale romper tratos?", guest: "Lady Arwen" },
    { id: 103, title: "Ep. 3: Mujeres en el Lore de Magic", duration: "52 min", date: "03 Octubre", description: "Analizamos la evolución de personajes femeninos icónicos, desde Serra hasta Liliana Vess.", guest: "Lorekeeper Val" },
    { id: 102, title: "Ep. 2: Superando el 'Imposter Syndrome'", duration: "38 min", date: "26 Septiembre", description: "Hablamos sobre cómo sentirte segura y validar tu espacio en tiendas competitivas.", guest: "Jueza Ana" }
  ],
  blog: {
    title: "Latest Articles",
    posts: [
      { id: 1, title: "Getting Started with Vue & Hugo", slug: "getting-started", date: "2026-02-05", excerpt: "How to integrate Vue.js with a headless Hugo CMS." },
      { id: 2, title: "Vertical Slicing Architecture", slug: "vertical-slicing", date: "2026-02-04", excerpt: "Why grouping by feature is better than by file type." }
    ]
  },
  "posts/getting-started": {
    title: "Getting Started with Vue & Hugo",
    date: "2026-02-05",
    content: "<p>This is the full content of the article. It would be HTML generated by Hugo from Markdown.</p>"
  },
  "posts/vertical-slicing": {
    title: "Vertical Slicing Architecture",
    date: "2026-02-04",
    content: "<p>Vertical slicing allows you to keep related code together. It scales much better!</p>"
  },
  manifesto: {
    title: "El Manifiesto de la Comunidad",
    quote: "\"En esta mesa, todas portamos corona\"",
    principles: [
      {
        number: "I",
        title: "La Excelencia del Respeto",
        body: "Declaramos que nuestro espacio es sagrado. La intolerancia, el acoso y la condescendencia son dragones que hemos desterrado de nuestras tierras. Aquí, la bondad es el hechizo más poderoso y el respeto es la única moneda de cambio aceptada."
      },
      {
        number: "II",
        title: "Magia sin Barreras",
        body: "No importa si tu mazo cuesta diez monedas o mil tesoros, o si empezaste a jugar ayer o hace décadas. El valor de una jugadora no reside en su colección, sino en su espíritu. Nos comprometemos a derribar muros y construir puentes de cristal para todas."
      },
      {
        number: "III",
        title: "La Narrativa Primero",
        body: "Jugamos para crear recuerdos. Celebramos la jugada brillante de la oponente tanto como la nuestra. En Ladies The Gathering, el objetivo final no es solo reducir vidas a cero, sino elevar la experiencia de juego a una forma de arte compartido."
      }
    ],
    footer_text: "Sellado y decretado por la comunidad de Ladies The Gathering."
  }
};

export async function getContent(slug: string): Promise<any> {
  // In production with Hugo, this might fetch `/${slug}/index.json`
  if (import.meta.env.DEV) {
    console.log(`[Mock] Fetching content for: ${slug}`);
    return new Promise((resolve) => {
      setTimeout(() => resolve(MOCKS[slug] || null), 500);
    });
  }
  
  // Real fetch implementation
  try {
    // Hugo outputs list pages at /section/index.json and home at /index.json
    const apiPath = slug === 'home' ? '/index.json' : `/${slug}/index.json`;
    
    // Handle single posts (e.g. posts/my-slug) -> /blog/my-slug/index.json or just /blog/my-slug.json
    // Hugo default for single pages depends on config. Usually /section/slug/index.json
    let url = `${import.meta.env.VITE_CMS_API_URL}${apiPath}`;
    
    if (slug.startsWith('posts/')) {
       // Example: slug="posts/getting-started" -> CMS="/blog/getting-started/index.json"
       const cleanSlug = slug.replace('posts/', '');
       url = `${import.meta.env.VITE_CMS_API_URL}/blog/${cleanSlug}/index.json`;
    }

    console.log(`[Content] Fetching: ${url}`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Status ${res.status}`);
    return await res.json();
  } catch (e) {
    console.error(`Failed to fetch content for ${slug}`, e);
    // Fallback to mock only in DEV if fetch fails
    if (import.meta.env.DEV) return MOCKS[slug] || null;
    return null;
  }
}
